services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=recipe
      - POSTGRES_USER=orlando
      - POSTGRES_PASSWORD=orjocagre
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

